# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_buyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12market_buyer.proto\"\x9b\x01\n\x0eSearchRequest1\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x33\n\ritem_category\x18\x02 \x01(\x0e\x32\x1c.SearchRequest1.ItemCategory\"A\n\x0cItemCategory\x12\x0f\n\x0b\x45LECTRONICS\x10\x00\x12\x0b\n\x07\x46\x41SHION\x10\x01\x12\n\n\x06OTHERS\x10\x02\x12\x07\n\x03\x41NY\x10\x03\"t\n\x04Item\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x14\n\x0cproduct_name\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x10\n\x08quantity\x18\x06 \x01(\x05\x12\x0e\n\x06rating\x18\x07 \x01(\x02\"\'\n\x0fSearchResponse1\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\"G\n\x0b\x42uyRequest1\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x15\n\rbuyer_address\x18\x03 \x01(\t\"W\n\x0c\x42uyResponse1\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.BuyResponse1.Status\"!\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"?\n\x15\x41\x64\x64ToWishListRequest1\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x15\n\rbuyer_address\x18\x02 \x01(\t\"k\n\x16\x41\x64\x64ToWishListResponse1\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.AddToWishListResponse1.Status\"!\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"J\n\x10RateItemRequest1\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x15\n\rbuyer_address\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x05\"a\n\x11RateItemResponse1\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.RateItemResponse1.Status\"!\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32\xdc\x01\n\x0c\x42uyerService\x12/\n\nSearchItem\x12\x0f.SearchRequest1\x1a\x10.SearchResponse1\x12&\n\x07\x42uyItem\x12\x0c.BuyRequest1\x1a\r.BuyResponse1\x12@\n\rAddToWishList\x12\x16.AddToWishListRequest1\x1a\x17.AddToWishListResponse1\x12\x31\n\x08RateItem\x12\x11.RateItemRequest1\x1a\x12.RateItemResponse1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_buyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHREQUEST1']._serialized_start=23
  _globals['_SEARCHREQUEST1']._serialized_end=178
  _globals['_SEARCHREQUEST1_ITEMCATEGORY']._serialized_start=113
  _globals['_SEARCHREQUEST1_ITEMCATEGORY']._serialized_end=178
  _globals['_ITEM']._serialized_start=180
  _globals['_ITEM']._serialized_end=296
  _globals['_SEARCHRESPONSE1']._serialized_start=298
  _globals['_SEARCHRESPONSE1']._serialized_end=337
  _globals['_BUYREQUEST1']._serialized_start=339
  _globals['_BUYREQUEST1']._serialized_end=410
  _globals['_BUYRESPONSE1']._serialized_start=412
  _globals['_BUYRESPONSE1']._serialized_end=499
  _globals['_BUYRESPONSE1_STATUS']._serialized_start=466
  _globals['_BUYRESPONSE1_STATUS']._serialized_end=499
  _globals['_ADDTOWISHLISTREQUEST1']._serialized_start=501
  _globals['_ADDTOWISHLISTREQUEST1']._serialized_end=564
  _globals['_ADDTOWISHLISTRESPONSE1']._serialized_start=566
  _globals['_ADDTOWISHLISTRESPONSE1']._serialized_end=673
  _globals['_ADDTOWISHLISTRESPONSE1_STATUS']._serialized_start=466
  _globals['_ADDTOWISHLISTRESPONSE1_STATUS']._serialized_end=499
  _globals['_RATEITEMREQUEST1']._serialized_start=675
  _globals['_RATEITEMREQUEST1']._serialized_end=749
  _globals['_RATEITEMRESPONSE1']._serialized_start=751
  _globals['_RATEITEMRESPONSE1']._serialized_end=848
  _globals['_RATEITEMRESPONSE1_STATUS']._serialized_start=466
  _globals['_RATEITEMRESPONSE1_STATUS']._serialized_end=499
  _globals['_BUYERSERVICE']._serialized_start=851
  _globals['_BUYERSERVICE']._serialized_end=1071
# @@protoc_insertion_point(module_scope)
