# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import market_buyer_pb2 as market__buyer__pb2


class BuyerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchItem = channel.unary_unary(
                '/BuyerService/SearchItem',
                request_serializer=market__buyer__pb2.SearchRequest1.SerializeToString,
                response_deserializer=market__buyer__pb2.SearchResponse1.FromString,
                )
        self.BuyItem = channel.unary_unary(
                '/BuyerService/BuyItem',
                request_serializer=market__buyer__pb2.BuyRequest1.SerializeToString,
                response_deserializer=market__buyer__pb2.BuyResponse1.FromString,
                )
        self.AddToWishList = channel.unary_unary(
                '/BuyerService/AddToWishList',
                request_serializer=market__buyer__pb2.AddToWishListRequest1.SerializeToString,
                response_deserializer=market__buyer__pb2.AddToWishListResponse1.FromString,
                )
        self.RateItem = channel.unary_unary(
                '/BuyerService/RateItem',
                request_serializer=market__buyer__pb2.RateItemRequest1.SerializeToString,
                response_deserializer=market__buyer__pb2.RateItemResponse1.FromString,
                )


class BuyerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToWishList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItem,
                    request_deserializer=market__buyer__pb2.SearchRequest1.FromString,
                    response_serializer=market__buyer__pb2.SearchResponse1.SerializeToString,
            ),
            'BuyItem': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyItem,
                    request_deserializer=market__buyer__pb2.BuyRequest1.FromString,
                    response_serializer=market__buyer__pb2.BuyResponse1.SerializeToString,
            ),
            'AddToWishList': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWishList,
                    request_deserializer=market__buyer__pb2.AddToWishListRequest1.FromString,
                    response_serializer=market__buyer__pb2.AddToWishListResponse1.SerializeToString,
            ),
            'RateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RateItem,
                    request_deserializer=market__buyer__pb2.RateItemRequest1.FromString,
                    response_serializer=market__buyer__pb2.RateItemResponse1.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BuyerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/SearchItem',
            market__buyer__pb2.SearchRequest1.SerializeToString,
            market__buyer__pb2.SearchResponse1.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuyItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/BuyItem',
            market__buyer__pb2.BuyRequest1.SerializeToString,
            market__buyer__pb2.BuyResponse1.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToWishList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/AddToWishList',
            market__buyer__pb2.AddToWishListRequest1.SerializeToString,
            market__buyer__pb2.AddToWishListResponse1.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/RateItem',
            market__buyer__pb2.RateItemRequest1.SerializeToString,
            market__buyer__pb2.RateItemResponse1.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
