# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import process_pb2 as process__pb2


class MasterMapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapPartition = channel.unary_unary(
                '/MasterMapper/MapPartition',
                request_serializer=process__pb2.MapPartitionRequest.SerializeToString,
                response_deserializer=process__pb2.MapPartitionResponse.FromString,
                )
        self.InvokeReducer = channel.unary_unary(
                '/MasterMapper/InvokeReducer',
                request_serializer=process__pb2.InvokeReducerRequest.SerializeToString,
                response_deserializer=process__pb2.InvokeReducerResponse.FromString,
                )
        self.GetInputData = channel.unary_unary(
                '/MasterMapper/GetInputData',
                request_serializer=process__pb2.GetInputDataRequest.SerializeToString,
                response_deserializer=process__pb2.GetInputDataResponse.FromString,
                )


class MasterMapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MapPartition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeReducer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInputData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterMapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapPartition': grpc.unary_unary_rpc_method_handler(
                    servicer.MapPartition,
                    request_deserializer=process__pb2.MapPartitionRequest.FromString,
                    response_serializer=process__pb2.MapPartitionResponse.SerializeToString,
            ),
            'InvokeReducer': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeReducer,
                    request_deserializer=process__pb2.InvokeReducerRequest.FromString,
                    response_serializer=process__pb2.InvokeReducerResponse.SerializeToString,
            ),
            'GetInputData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInputData,
                    request_deserializer=process__pb2.GetInputDataRequest.FromString,
                    response_serializer=process__pb2.GetInputDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MasterMapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterMapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MapPartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterMapper/MapPartition',
            process__pb2.MapPartitionRequest.SerializeToString,
            process__pb2.MapPartitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InvokeReducer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterMapper/InvokeReducer',
            process__pb2.InvokeReducerRequest.SerializeToString,
            process__pb2.InvokeReducerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInputData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterMapper/GetInputData',
            process__pb2.GetInputDataRequest.SerializeToString,
            process__pb2.GetInputDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
